services:

  mysql:
    image: 'mysql:8.0.33'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_USER=myuser'
      - 'MYSQL_ROOT_PASSWORD=secret'
    ports:
      - '3306:3306'
    volumes:
      - ./sql-init/init.sql:/docker-entrypoint-initdb.d/init.sql

